listen:
    host: ""
    port: 2333
    log_level: debug
    mode: ""
    max_concurrent: 10
    queue_limit_max_concurrent: 10
database:
    driver: mysql
    dsn: goserver:goserver@tcp(139.159.145.78:3306)/goserver?charset=utf8mb4&parseTime=True&loc=Local
#    dsn: user:pwd@tcp(localhost:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local
    max_open_conns: 25 # 最大打开连接数
    max_idle_conns: 10 # 最大空闲连接数
    conn_max_lifetime: 5m # 连接最大生命周期
    conn_max_idle_time: 1m # 连接最大空闲时间
    log_level: warn
    auto_migrate: true
    prepare_stmt: false
    disable_nested_transaction: false
    connect_timeout: 15s
    ping_interval: 1m
redis:
    addr: 139.159.145.78:6379
    password: "redis_KF26xN"
    db: 0
    pool_size: 10
    min_idle_conns: 5
    max_retries: 3
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
    idle_timeout: 5m
admin_user:
    username: admin
    password: 123456
    nickname: 管理员
    email: admin@example.com





